# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cccb20690fa2c6d6b327572fe0fdf7485dc0e0440588662aca68953bfc3dd35a1e178b23b1c743d6e33f7c9ae5b25866b7cd1daa5709daa12b5526ba0ea5aea3

test:
  secret_key_base: 79593d23e9e29b059ffa7352949d8a1869fa04d48e1904ccd5a12d036c95c8eaed8600de7cf053a494af4c24538464aee67f908d8a94ab68f89c463837b3a3dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
